version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=geomemories
      - POSTGRES_USER=geo_user
      - POSTGRES_PASSWORD=geo_password
    ports:
      - "5432:5432"

  # web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   ... (Add your Django service configuration here)

volumes:
  postgres_data: